(function(){
  const SPELLING = {
    1: [
      {w:'cat',h:'A furry pet that purrs'},{w:'dog',h:'A pet that barks'},{w:'hat',h:'You wear it on your head'},
      {w:'sun',h:'It shines in the sky'},{w:'mum',h:'Your mother'},{w:'dad',h:'Your father'},
      {w:'bed',h:'You sleep in it'},{w:'red',h:'The colour of a fire engine'},{w:'cup',h:'You drink from it'},
      {w:'big',h:'Not small'},{w:'pig',h:'A pink farm animal'},{w:'hen',h:'A bird on the farm'},
      {w:'ten',h:'The number after nine'},{w:'pen',h:'You write with it'},{w:'fox',h:'A wild animal with a bushy tail'},
      {w:'box',h:'You put things inside it'},{w:'bus',h:'A big vehicle for people'},{w:'run',h:'Moving fast on your feet'},
      {w:'fun',h:'Something that makes you happy'},{w:'sit',h:'The opposite of stand'},
      {w:'log',h:'A piece of wood'},{w:'top',h:'The highest part'},{w:'pot',h:'For cooking soup'},
      {w:'hot',h:'Not cold'},{w:'net',h:'Used to catch fish'},{w:'wet',h:'Covered in water'},
      {w:'map',h:'Shows you where to go'},{w:'jam',h:'Sweet spread for toast'},{w:'van',h:'A delivery vehicle'},
      {w:'pan',h:'For frying eggs'},{w:'man',h:'A grown-up boy'},{w:'can',h:'Beans come in one'},
      {w:'bug',h:'A tiny crawling creature'},{w:'rug',h:'A mat on the floor'},{w:'hug',h:'You wrap your arms around someone'},
      {w:'pin',h:'Sharp and pointy'},{w:'win',h:'The opposite of lose'},{w:'bin',h:'For putting rubbish in'},
      {w:'bat',h:'Flies at night'},{w:'rat',h:'A mouse but bigger'},{w:'mat',h:'You wipe your feet on it'},
      {w:'tap',h:'Water comes out of it'},{w:'nap',h:'A short sleep'},{w:'lip',h:'Part of your mouth'},
      {w:'tip',h:'The very end of something'},{w:'dig',h:'Making a hole in the ground'},{w:'fig',h:'A sweet fruit'},
      {w:'cob',h:'Corn on the...'},{w:'sob',h:'To cry hard'},{w:'hop',h:'Jump on one foot'},{w:'mop',h:'For cleaning the floor'},
      {w:'bee',h:'Makes honey'},{w:'egg',h:'Comes from a chicken'},{w:'ant',h:'Tiny insect'},{w:'owl',h:'Night bird'},{w:'cow',h:'Gives us milk'},
      {w:'pie',h:'Baked with pastry'},{w:'toy',h:'Something to play with'},{w:'key',h:'Opens a lock'},{w:'web',h:'A spider makes one'},
      {w:'mud',h:'Wet dirt'},{w:'gum',h:'You chew it'},{w:'zip',h:'Fastens your jacket'},{w:'fog',h:'Thick mist'},{w:'den',h:'An animal home'},
      {w:'vet',h:'Animal doctor'},{w:'gem',h:'A precious stone'}
    ],
    2: [
      {w:'play',h:'Having fun with games'},{w:'stay',h:'Not leaving'},{w:'tree',h:'Tall with leaves and branches'},
      {w:'moon',h:'Shines at night'},{w:'book',h:'You read it'},{w:'rain',h:'Water falling from clouds'},
      {w:'boat',h:'Floats on water'},{w:'coat',h:'Keeps you warm outside'},{w:'road',h:'Cars drive on it'},
      {w:'fish',h:'Lives underwater'},{w:'ship',h:'A big boat'},{w:'shop',h:'Where you buy things'},
      {w:'them',h:'Those people'},{w:'when',h:'At what time?'},{w:'each',h:'Every one'},
      {w:'much',h:'A lot of something'},{w:'away',h:'Not here'},{w:'home',h:'Where you live'},
      {w:'some',h:'A few, not all'},{w:'here',h:'In this place'},{w:'they',h:'Those people'},
      {w:'said',h:'Spoke words'},{w:'about',h:'On the subject of'},{w:'water',h:'You drink it'},
      {w:'where',h:'In what place?'},{w:'first',h:'Number one'},{w:'other',h:'A different one'},
      {w:'right',h:'Correct, not wrong'},{w:'their',h:'Belonging to them'},{w:'would',h:'Past tense of will'},
      {w:'could',h:'Was able to'},{w:'under',h:'Below something'},{w:'after',h:'Following in time'},
      {w:'think',h:'Use your brain'},{w:'which',h:'What one?'},{w:'these',h:'The ones right here'},
      {w:'night',h:'When it is dark'},{w:'light',h:'Opposite of dark'},{w:'sleep',h:'Eyes closed, resting'},
      {w:'green',h:'The colour of grass'},{w:'brown',h:'The colour of chocolate'},{w:'black',h:'The darkest colour'},
      {w:'white',h:'The colour of snow'},{w:'stone',h:'A small rock'},{w:'flame',h:'Fire makes this'},
      {w:'brave',h:'Not afraid'},{w:'dream',h:'You have them when you sleep'},{w:'cloud',h:'White and fluffy in the sky'},
      {w:'happy',h:'Feeling good'},{w:'funny',h:'Makes you laugh'},{w:'carry',h:'Hold and move something'},{w:'lunch',h:'Midday meal'},
      {w:'bridge',h:'Goes over a river'},{w:'quiet',h:'Not loud'},{w:'wrong',h:'Not correct'},{w:'smile',h:'You do it when happy'},
      {w:'climb',h:'Go up something'},{w:'giant',h:'Very very big person'},{w:'fairy',h:'Magical tiny person'},{w:'beach',h:'Sandy place by the sea'},
      {w:'world',h:'The whole planet'},{w:'fresh',h:'New and clean'},{w:'story',h:'A tale or adventure'},{w:'horse',h:'You can ride it'},
      {w:'music',h:'Sounds that make songs'},{w:'clock',h:'Tells the time'},{w:'plate',h:'You eat food from it'},{w:'guess',h:'Try to get the answer'}
    ],
    3: [
      {w:'beautiful',h:'Very pretty'},{w:'different',h:'Not the same'},{w:'important',h:'Really matters'},
      {w:'together',h:'With each other'},{w:'beginning',h:'The start'},{w:'knowledge',h:'What you know'},
      {w:'adventure',h:'An exciting journey'},{w:'excellent',h:'Really, really good'},{w:'wonderful',h:'Amazing and great'},
      {w:'favourite',h:'The one you like best'},{w:'discovery',h:'Finding something new'},{w:'difficult',h:'Hard to do'},
      {w:'education',h:'Learning at school'},{w:'imaginary',h:'Not real, made up'},{w:'character',h:'A person in a story'},
      {w:'community',h:'People living together'},{w:'experiment',h:'A scientific test'},{w:'necessary',h:'You need it'},
      {w:'dangerous',h:'Could hurt you'},{w:'celebrate',h:'Have a party for something'},{w:'disappear',h:'Vanish, go away'},
      {w:'especially',h:'More than usual'},{w:'government',h:'People who run the country'},{w:'incredible',h:'Hard to believe, amazing'},
      {w:'literature',h:'Books and stories'},{w:'mysterious',h:'Strange and unknown'},{w:'naturally',h:'In a normal way'},
      {w:'operation',h:'Surgery or a planned action'},{w:'perfectly',h:'Without any mistakes'},{w:'questions',h:'Things you ask'},
      {w:'recommend',h:'Suggest something good'},{w:'seriously',h:'Not joking'},{w:'temporary',h:'Not forever'},
      {w:'understand',h:'Get the meaning'},{w:'vegetable',h:'Carrots and broccoli are these'},{w:'surprise',h:'You did not expect it'},
      {w:'strength',h:'Being strong'},{w:'although',h:'Even though'},{w:'creature',h:'A living animal or being'},
      {w:'elephant',h:'The biggest land animal'},{w:'shoulder',h:'Between your neck and arm'},{w:'daughter',h:'A female child'},
      {w:'mountain',h:'Very high land'},{w:'sandwich',h:'Bread with filling'},{w:'hospital',h:'Where doctors work'},
      {w:'tomorrow',h:'The day after today'},{w:'calendar',h:'Shows days and months'},{w:'dinosaur',h:'Extinct giant reptile'},
      {w:'everyone',h:'All the people'},{w:'language',h:'English or French for example'},{w:'princess',h:'A royal daughter'},
      {w:'orchestra',h:'A large group of musicians'},{w:'chocolate',h:'Sweet brown treat'},{w:'telescope',h:'See things far away'},
      {w:'invisible',h:'Cannot be seen'},{w:'desperate',h:'In great need'},{w:'continent',h:'A large landmass like Africa'},
      {w:'passenger',h:'Someone riding in a vehicle'},{w:'companion',h:'A friend or partner'},{w:'guarantee',h:'A promise it will work'},
      {w:'equipment',h:'Tools and machines for a job'},{w:'brilliant',h:'Very clever or shining brightly'},{w:'catalogue',h:'A list of items'},
      {w:'furniture',h:'Tables, chairs, beds etc'},{w:'elaborate',h:'Very detailed and complex'},{w:'hurricane',h:'A powerful tropical storm'},
      {w:'nightmare',h:'A scary dream'},{w:'volunteer',h:'Someone who helps for free'},{w:'threshold',h:'The entrance or doorway'},
      {w:'abundance',h:'A very large quantity'}
    ]
  }

  const WORD_EMOJI = {
    'cat':'1f431',
    'dog':'1f436',
    'hat':'1f3a9',
    'sun':'2600',
    'mum':'1f469',
    'dad':'1f468',
    'bed':'1f6cf',
    'red':'1f534',
    'cup':'2615',
    'big':'1f418',
    'pig':'1f437',
    'hen':'1f414',
    'ten':'1f51f',
    'pen':'270f',
    'fox':'1f98a',
    'box':'1f4e6',
    'bus':'1f68c',
    'run':'1f3c3',
    'fun':'1f389',
    'sit':'1fa91',
    'log':'1fab5',
    'top':'2b06',
    'pot':'1fa98',
    'hot':'1f525',
    'net':'1f3d0',
    'wet':'1f4a7',
    'map':'1f5fa',
    'jam':'1f353',
    'van':'1f690',
    'pan':'1f373',
    'man':'1f9d1',
    'can':'1f96b',
    'bug':'1f41b',
    'rug':'1f9f6',
    'hug':'1f917',
    'pin':'1f4cc',
    'win':'1f3c6',
    'bin':'1f5d1',
    'bat':'1f987',
    'rat':'1f400',
    'mat':'1f9f9',
    'tap':'1f6b0',
    'nap':'1f634',
    'lip':'1f444',
    'tip':'261d',
    'dig':'26cf',
    'fig':'1f95d',
    'cob':'1f33d',
    'sob':'1f622',
    'hop':'1f407',
    'mop':'1f9f9',
    'play':'1f3ae',
    'stay':'1f3e0',
    'tree':'1f333',
    'moon':'1f319',
    'book':'1f4d6',
    'rain':'1f327',
    'boat':'26f5',
    'coat':'1f9e5',
    'road':'1f6e3',
    'fish':'1f41f',
    'ship':'1f6a2',
    'shop':'1f6cd',
    'them':'1f465',
    'when':'231a',
    'each':'261d',
    'much':'1f4af',
    'away':'1f44b',
    'home':'1f3e0',
    'some':'1f90f',
    'here':'1f4cd',
    'they':'1f465',
    'said':'1f4ac',
    'about':'1f4d6',
    'water':'1f4a7',
    'where':'1f50d',
    'first':'1f947',
    'other':'1f449',
    'right':'2705',
    'their':'1f46a',
    'would':'1f4ad',
    'could':'1f4ad',
    'under':'1f447',
    'after':'23e9',
    'think':'1f9e0',
    'which':'1f914',
    'these':'1f449',
    'night':'1f319',
    'light':'1f4a1',
    'sleep':'1f634',
    'green':'1f49a',
    'brown':'1f7e4',
    'black':'2b1b',
    'white':'2b1c',
    'stone':'1faa8',
    'flame':'1f525',
    'brave':'1f9b8',
    'dream':'1f4ad',
    'cloud':'2601',
    'happy':'1f604',
    'funny':'1f602',
    'carry':'1f3cb',
    'lunch':'1f96a',
    'beautiful':'1f338',
    'different':'1f500',
    'important':'2757',
    'together':'1f91d',
    'beginning':'1f3ac',
    'knowledge':'1f4da',
    'adventure':'1f5fa',
    'excellent':'1f31f',
    'wonderful':'2728',
    'favourite':'2764',
    'discovery':'1f50e',
    'difficult':'1f4aa',
    'education':'1f393',
    'imaginary':'1f984',
    'character':'1f9d1',
    'community':'1f3d8',
    'experiment':'1f52c',
    'necessary':'2705',
    'dangerous':'26a0',
    'celebrate':'1f389',
    'disappear':'1f47b',
    'especially':'2b50',
    'government':'1f3db',
    'incredible':'1f929',
    'literature':'1f4da',
    'mysterious':'1f575',
    'naturally':'1f33f',
    'operation':'1f3e5',
    'perfectly':'1f4af',
    'questions':'2753',
    'recommend':'1f44d',
    'seriously':'1f9d0',
    'temporary':'23f3',
    'understand':'1f9e0',
    'vegetable':'1f955',
    'surprise':'1f381',
    'strength':'1f4aa',
    'although':'1f914',
    'creature':'1f432',
    'elephant':'1f418',
    'shoulder':'1f933',
    'daughter':'1f467',
    'mountain':'26f0',
    'sandwich':'1f96a',
    'hospital':'1f3e5',
    'tomorrow':'1f305',
    'calendar':'1f4c5',
    'dinosaur':'1f995',
    'everyone':'1f46b',
    'language':'1f5e3',
    'princess':'1f478'
  }

  window.ClassmatesSpelling = {
    SPELLING: SPELLING,
    WORD_EMOJI: WORD_EMOJI
  }
})()
